services:
  - type: web
    name: music-downloader
    env: node
    plan: free
    buildCommand: ./render-build.sh
    startCommand: ./start-render.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 20